library(dplyr)
temp <- tempfile()
download.file("https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip", temp)
theData <- read.table(unz(temp, "household_power_consumption.txt"), header = TRUE, sep=";", na.strings = "?")
unlink(temp)
theData$Date <- as.Date(theData$Date, "%d/%m/%Y")
myDF<- filter(theData, Date== "2007-02-01" | Date =="2007-02-02")
myDF$Time <- strptime(paste(myDF$Date, myDF$Time), "%Y-%m-%d %H:%M:%S")
rm(theData)
png("Plot 4.png")
par(mfrow= c(2,2))
plot(myDF$Time, myDF$Global_active_power, type = "l", xlab = "", ylab = "Global Active Power")
with(myDF, plot(Time,Voltage, type = "l"))
plot(myDF$Time, myDF$Sub_metering_1, type= "n", ylab = "Energy Sub metering", xlab="")
lines(myDF$Time, myDF$Sub_metering_1)
lines(myDF$Time, myDF$Sub_metering_2, col="red")
lines(myDF$Time, myDF$Sub_metering_3, col="blue")
legend("topright", legend =c("Sub_metering _1", "Sub_metering_2", "Sub_metering_3"), col = c("black","red", "blue" ), bty="n", lty = c(1, 1, 1), cex= c(0.8, 0.8, 0.8))
with(myDF, plot(Time,Global_reactive_power, type = "l"))
dev.off()