library(dplyr)
temp <- tempfile()
download.file("https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip", temp)
theData <- read.table(unz(temp, "household_power_consumption.txt"), header = TRUE, sep=";", na.strings = "?")
unlink(temp)
theData$Date <- as.Date(theData$Date, "%d/%m/%Y")
myDF<- filter(theData, Date== "2007-02-01" | Date =="2007-02-02")
myDF$Time <- strptime(paste(myDF$Date, myDF$Time), "%Y-%m-%d %H:%M:%S")
rm(theData)
png("Plot 2.png")
plot(myDF$Time, myDF$Global_active_power, type = "l", xlab = "", ylab = "Global Active Power (kilowatts)")
dev.off()